/*
Copyright or © or Copr. Jason Mahdjoub (04/02/2016)

jason.mahdjoub@distri-mind.fr

This software (Utils) is a computer program whose purpose is to give several kind of tools for developers 
(ciphers, XML readers, decentralized id generators, etc.).

This software is governed by the CeCILL-C license under French law and
abiding by the rules of distribution of free software.  You can  use, 
modify and/ or redistribute the software under the terms of the CeCILL-C
license as circulated by CEA, CNRS and INRIA at the following URL
"http://www.cecill.info". 

As a counterpart to the access to the source code and  rights to copy,
modify and redistribute granted by the license, users are provided only
with a limited warranty  and the software's author,  the holder of the
economic rights,  and the successive licensors  have only  limited
liability. 

In this respect, the user's attention is drawn to the risks associated
with loading,  using,  modifying and/or developing or reproducing the
software by the user in light of its specific status of free software,
that may mean  that it is complicated to manipulate,  and  that  also
therefore means  that it is reserved for developers  and  experienced
professionals having in-depth computer knowledge. Users are therefore
encouraged to load and test the software's suitability as regards their
requirements in conditions enabling the security of their systems and/or 
data to be ensured and,  more generally, to use and operate it in the 
same conditions as regards security. 

The fact that you are presently reading this means that you have had
knowledge of the CeCILL-C license and that you accept its terms.
 */
package com.distrimind.util.crypto;

import java.security.SecureRandom;

/**
 * 
 * @author Jason Mahdjoub
 * @version 1.0
 * @since Utils 2.0
 */
public abstract class AbstractSecureRandom extends SecureRandom
{
    /**
     * 
     */
    private static final long serialVersionUID = 8080761472279881205L;

    private final SecureRandomType type;

    AbstractSecureRandom(SecureRandomType type)
    {
	super(null, null);
	this.type = type;
    }

    /**
     * Returns the specified number of seed bytes.
     * 
     * @param numBytes
     *            number of seed bytes to get
     * 
     * @return an array containing the seed bytes
     */
    @Override
    public abstract byte[] generateSeed(int numBytes);

    /**
     * Returns the algorithm name used or "unknown" when the algorithm used
     * couldn't be determined (as when constructed by the protected 2 argument
     * constructor).
     *
     */
    @Override
    public abstract String getAlgorithm();

    public abstract gnu.vm.jgnu.security.SecureRandom getGnuSecureRandom();

    public abstract java.security.SecureRandom getJavaNativeSecureRandom();

    public final SecureRandomType getType()
    {
	return type;
    }

    /**
     * Generates a user specified number of bytes. This function is the basis
     * for all the random functions.
     * 
     * @param bytes
     *            array to store generated bytes in
     */
    @Override
    public abstract void nextBytes(byte[] bytes);

    /**
     * Seeds the SecureRandom. The class is re-seeded for each call and each
     * seed builds on the previous seed so as not to weaken security.
     * 
     * @param seed
     *            seed bytes to seed with
     */
    @Override
    public abstract void setSeed(byte[] seed);

    @Override
    public abstract void setSeed(long seed);

}
